version: '3'

services:
  backend:
    build:
      context: ./mosega_backend/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"

  frontend:
    build:
      context: ./mosega_frontend/
    volumes:
    - build_folder:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - 6000:6000
    volumes:
      - ./webServer/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  build_folder: