export const LOAD_POLICIES = 'LOAD_POLICIES';
export const SELECT_POLICY = 'SELECT_POLICY';
export const LOAD_TERMS = 'LOAD_TERMS';
export const SELECT_TERM = 'SELECT_TERM';
export const ADD_SIMILARITY_QUERY = 'ADD_SIMILARITY_QUERY';
export const REMOVE_SIMILARITY_QUERY = 'REMOVE_SIMILARITY_QUERY';
export const PRE_CLUSTER_QUERY = 'PRE_CLUSTER_QUERY';
export const SIMILAR_SET_QUERY = 'SIMILAR_SET_QUERY';