# Generated by Django 2.2.6 on 2020-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermHighLevel',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('TermID', models.IntegerField()),
                ('TermURL', models.CharField(max_length=300)),
                ('TermTitle', models.CharField(max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TermID', models.IntegerField()),
                ('SectionID', models.IntegerField()),
                ('heading', models.CharField(max_length=1000)),
                ('text', models.TextField()),
            ],
            options={
                'unique_together': {('TermID', 'SectionID')},
            },
        ),
    ]
