# Generated by Django 2.2.3 on 2019-09-09 13:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyModel',
            fields=[
                ('PrivacyPolicy', jsonfield.fields.JSONField(default=dict)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
