database :
  db_engine: 'djongo'
  db_name: 'mosega-dev'
  db_host: 'mongodb+srv://mosega_super_user:mosegasuper@aselacluster-nfyzw.mongodb.net/test?retryWrites=true&w=majority'
  db_username: 'mosega'
  db_password: 'mosegasuper'


api:

  title: 'api'
  documentation: 'api_doc'
  current_version: 'v1'

  backend:

    SampleAPI:
      view: 'SampleAPI'
      name: 'Sample'

    TextPreProcessing:
      view: 'TextPreProcessingAPI'
      name: 'Text+Pre+Processing'

    Policy:
      view: 'PrivacyPolicyAPI'
      name: 'PrivacyPolicy'

    Term:
      view: 'TermsAndConditionsAPI'
      name: 'Terms+And+Conditions'

logging:
  path: 'Log/mosega-functional.log'
  directory: 'Log'
  file: 'mosega-functional.log'
  format:  '%(levelname)s : %(funcName)s : %(asctime)s : %(message)s'

policyFiles:
  path: 'PreProcessing/HTML/policies'

termFiles:
  path: 'PreProcessing/HTML/terms'

