database :
  engine: 'django.db.backends.mysql'
  dbname: 'mosega'
  host: '172.17.0.1'
  port: '3306'
  username: 'mosega'
  password: 'mosegasuper'


api:

  title: 'api'
  documentation: 'api_doc'
  current_version: 'v1'

  backend:

    SampleAPI:
      view: 'SampleAPI'
      name: 'Sample'

    TextPreProcessing:
      view: 'TextPreProcessingAPI'
      name: 'Text+Pre+ProcessingAPI'

    Policy:
      view: 'PrivacyPolicyAPI'
      name: 'policy'

    Term:
      view: 'TermsAndConditionsAPI'
      name: 'term'

    Processing:
      view: 'ProcessingAPI'
      name: 'processing'

logging:
  path: 'Log/mosega-functional.log'
  directory: 'Log'
  file: 'mosega-functional.log'
  format:  '%(levelname)s : %(funcName)s : %(asctime)s : %(message)s'

policyFiles:
  path: 'PreProcessing/HTML/policies/policy.txt'

termFiles:
  path: 'PreProcessing/HTML/terms/term.txt'

temporaryFile:
  path: 'PreProcessing/Text/temp.txt'
