version: "2"
services:
  django:
    container_name: mosega_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: mosega_backend
    stdin_open: true
    tty: true
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
